# Generated by Django 4.2.9 on 2024-04-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0002_alter_question_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="number",
            field=models.IntegerField(
                blank=True,
                help_text="номер для сортировки вопроса",
                null=True,
                unique=True,
                verbose_name="номер",
            ),
        ),
    ]
